import '../globals.css';
import type { Metadata } from 'next';

export const metadata: Metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
};

export default function RootLayout({
   children,
}: {
   children: React.ReactNode;
}) {
   return (
      <html lang='en'>
         <body className='font-secondaryFont text-neutral bg-base-200 min-h-screen flex flex-col'>
            {children}
         </body>
      </html>
   );
}
