import '../globals.css';
import type { Metadata } from 'next';
import Navbar from '@/components/Navbar';

export const metadata: Metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
};

export default function RootLayout({
   children,
}: {
   children: React.ReactNode;
}) {
   return (
      <html lang='en'>
         <body className='font-primaryFont text-black bg-violet-100 min-h-screen flex'>
            <Navbar />
            <div className='w-full min-h-[100vh]'>{children}</div>
         </body>
      </html>
   );
}
