import '../globals.css';
import type { Metadata } from 'next';
import AdminSidebar from '@/components/AdminSidebar';
import AdminNavbar from '@/components/AdminNavbar';
import Drawer from '@/components/Drawer';

export const metadata: Metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
};

export default function RootLayout({
   children,
}: {
   children: React.ReactNode;
}) {
   return (
      <html lang='en'>
         <body className='font-secondaryFont text-black bg-gray-100 min-h-screen flex flex-col'>
            <AdminNavbar />
            <Drawer contentPage={children} menu={<AdminSidebar />} />
         </body>
      </html>
   );
}
