import '../globals.css';
import type { Metadata } from 'next';
import AdminSidebar from '@/components/AdminSidebar';

export const metadata: Metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
};

export default function RootLayout({
   children,
}: {
   children: React.ReactNode;
}) {
   return (
      <html lang='en'>
         <body className='font-secondaryFont text-black bg-gray-100 min-h-screen flex'>
            <AdminSidebar />
            <div className='w-full min-h-[100vh] overflow-x-auto'>
               {children}
            </div>
         </body>
      </html>
   );
}
